#Examples:
spring:
  datasource:
    url: jdbc:postgresql://localhost:/discordbot
    username: postgres
    password: #####
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ABC@gmail.com
    password: "###"  # Verifique se a senha está correta e sem espaços extras
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
